//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub mod prelude;

pub mod g_appusers;
pub mod g_audittrail;
pub mod g_configure;
pub mod g_releases;
pub mod g_rules;
pub mod g_workspaces;
