//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub use super::g_appusers::Entity as GAppusers;
pub use super::g_audittrail::Entity as GAudittrail;
pub use super::g_configure::Entity as GConfigure;
pub use super::g_releases::Entity as GReleases;
pub use super::g_rules::Entity as GRules;
pub use super::g_workspaces::Entity as GWorkspaces;
